Coachmark component (WIP)
seb-oss/green pull request #1386
Opened 2024-05-23 10:38 UTC by kobraan

Draft for adding a new coachmark component to Green

2024-08-07 08:05 UTC, vsjolander requested changes
Great work and thank you for contributing! Added some requested changes and thoughts that I would like you feedback on.

Here are some other things that came to mind when looking at this PR:
At the moment I don't see a big difference between this component and the tooltip component in terms of functionality.

Coachmark probably should use tooltip under the hood but then add additional functionality like creating and managing multiple coachmarks, handling backdrop, scrubbing through coachmarks or something along those lines.. Would love to hear your take in this aswell!

I think this is a fine first iteration of the coachmark if we make the changes to slots and API and then in next iteration we can look at breaking out tooltip and see what functionality coachmark should have.

2024-08-07 08:17 UTC, kobraan commented on libs/core/src/components/coachmark/coachmark.stories.ts
> +            <gds-coachmark .coachmark=${coachmarkExample}>
@osamaalmidani Can you take a look at this?

2024-08-07 08:17 UTC, kobraan commented on libs/core/src/components/coachmark/coachmark.stories.ts
> +let coachmarkExample = {
@osamaalmidani Can you take a look at this?

2024-08-07 08:18 UTC, kobraan commented on libs/core/src/components/coachmark/coachmark.ts
> +    document.addEventListener('click', () => {
Yeah it was requested by CX, that it should be closed no matter where you click, but it can be configurable as well

2024-08-07 08:27 UTC, kobraan commented on libs/core/src/components/coachmark/coachmark.ts
> +          <slot name="body"></slot>
Do you mean just merging the body and footer slots?

2024-08-07 08:29 UTC, kobraan commented on libs/core/src/components/coachmark/coachmark.ts
> +      !isOverlapping && !isOutOfBound && isVisible && window.innerWidth > 580
Checking with CX, @osamaalmidani do you know more perhaps?

2024-08-12 10:59 UTC, vsjolander approved these changes

2024-08-12 11:01 UTC, merged