Feat/react-segmented-control-component
seb-oss/green pull request #1479
Opened 2024-07-04 16:05 UTC by terrance456

- React wrapper for green core segmented control 

![image](https://github.com/seb-oss/green/assets/92840841/698f38b4-7b67-47eb-835d-7263fd9135f9)

2024-07-04 16:13 UTC, ethan-qsh approved these changes

2024-07-04 21:57 UTC, kaylesj4 approved these changes

2024-07-05 09:16 UTC, splashdust requested changes
Just found a minor nit-pick, but other than that it looks great. Superb work!

2024-07-05 09:16 UTC, splashdust commented on libs/react/src/lib/segmented-control/segmented-control.tsx
> +  const onControlChange = (event: Event) => {
For consistency, I think `onChange` should just be forwarded directly here, and let the consumer deal with the event. That's how it works in the other wrappers, unless backwards-compatiblity reasons prevent it, and it's also more in line with how events work in native components, like `<input>` and `<button>`.

2024-07-05 10:19 UTC, splashdust approved these changes
Woho! Thank you for contributing to Green! 💚

2024-07-05 10:33 UTC, merged