Feat/react-pagination-component
seb-oss/green pull request #1501
Opened 2024-07-20 13:06 UTC by terrance456

![image](https://github.com/user-attachments/assets/be829a7f-449f-4569-bd72-3449ffe48f59)

2024-07-22 02:30 UTC, kaylesj4 approved these changes

2024-07-22 02:34 UTC, ethan-qsh approved these changes

2024-08-06 08:48 UTC, vsjolander requested changes
Looks good!

However there's one issue with tab focus when using a-tags. See inline comment.

2024-08-06 08:56 UTC, terrance456 commented on libs/react/src/lib/pagination/pagination.tsx
> +              <a
Totally agree in using button but the chlorophyll styling was added only for anchor specific and angular component is also using anchor tags. So wasn't sure if we should change it.

2024-08-12 11:04 UTC, vsjolander commented on libs/react/src/lib/pagination/pagination.tsx
> +              <a
Yea, looks like this is how it was done in the [angular component](https://storybook.seb.io/latest/angular/?path=/docs/components-navigation-pagination--documentation).

Ok for now! (until replaced with a core web component)

2024-09-17 14:26 UTC, EldRoos commented
Some minor chlorophyll changes. This pull request should not be effected.
https://github.com/seb-oss/green/pull/1599

2025-03-26 08:47 UTC, EldRoos commented
I get this error when trying to run react:storybook:

`ERROR in ./libs/react/src/lib/pagination/pagination.stories.mdx 15:4
Module parse failed: Unexpected token (15:4)`

2025-06-11 07:57 UTC, closed without merging