Docs:update cookie consent design
seb-oss/green pull request #1825
Opened 2024-11-21 14:27 UTC by IsabelleLof

This PR updates the design of the cookie consent to match the Green Design

2024-12-02 08:57 UTC, splashdust requested changes
Superbra jobbat överlag! 💯 
Hittade bara några småsaker som vore bra att kolla på innan vi stänger denna:

2024-12-02 08:57 UTC, splashdust commented on apps/docs/utils/consent/config.js
> +            'Hi, this website uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it. The latter will be set only after consent. <button typ
Du kan ta bort knappen här, eftersom den inte fyller någon funktion:

`<button type="button" data-cc="c-settings" class="cc-link">Let me choose</button>`

2024-12-02 08:57 UTC, splashdust commented on apps/docs/utils/consent/config.js
> +  // onFirstAction: function (user_preferences, cookie) {
Du kan ta bort denna utkommenterade kod eftersom den inte behövs längre.

2024-12-02 08:57 UTC, splashdust commented on apps/docs/utils/consent/config.js
> +  // onAccept: function (cookie) {
Samma här

2024-12-02 08:57 UTC, splashdust commented on apps/docs/utils/consent/config.js
> +  // onChange: function (cookie, changed_preferences) {
Och här :)

2024-12-02 08:57 UTC, splashdust commented on apps/docs/utils/consent/consent.tsx
> +      {/* <GdsFlex align-items="center" justify-content="center" >
Detta kan du ta bort också

2024-12-03 14:32 UTC, IsabelleLof commented
Have not changed the padding in the size of the cookie consent yet

2024-12-10 19:39 UTC, IsabelleLof commented
Not done yet :)

2024-12-19 14:47 UTC, splashdust approved these changes
Nu ser det bra ut!
Bra jobbat!! 🙌

2024-12-19 14:48 UTC, merged