Field Base: Select
seb-oss/green pull request #1876
Opened 2024-12-16 10:04 UTC by astrit

2025-01-28 10:07 UTC, splashdust requested changes
Overall it looks super good! Added a few nit picks in the review comments.

Additionally, there seem to be some events related issue. It seems like the value is 'lagging behind' and returning the previously selected one. I added it to the React and Angular examples, so you can have a look at it there in the context of a form with other components.

And one last thing, since this is a brand new component, it would be good to mark it a beta!

2025-01-29 15:49 UTC, astrit commented on libs/core/src/components/select/select.ts
> +  placeholder = ''
The value issue has been fixed now! 
Placeholder removed as I agree it should not be there.

2025-01-29 15:51 UTC, astrit commented
> Overall it looks super good! Added a few nit picks in the review comments.
> 
> Additionally, there seem to be some events related issue. It seems like the value is 'lagging behind' and returning the previously selected one. I added it to the React and Angular examples, so you can have a look at it there in the context of a form with other components.
> 
> And one last thing, since this is a brand new component, it would be good to mark it a beta!

Thank you very much for tremendous feedback! 
As noted all the previous issues have been fixed including the value! 
The beta status was there all along not sure if is missing somewhere else ? 
I improved a bit the documentation should be good enough!

2025-01-31 13:14 UTC, splashdust requested changes

2025-02-06 14:41 UTC, splashdust approved these changes

2025-02-06 14:54 UTC, merged